centauro:
   contacts: # structure where all contacts are stored
      contact1: # refer to the first contact
         name: front_left_leg # optional, human-readable name of a contact
         end_frame: knee_1 # required, name of a urdf link that is in a contact
         position: [0, 0, -0.30] # required, position of a contact point in the reference frame
         constraint_matrix: # required, at least one subelement is required to initialize the contact, normal of a force/moment constraint
            force_1: [0, 0, 0, 1, 0, 0] # direction of a first contraint on force 
            force_2: [0, 0, 0, 0, 1, 0] # direction of a second contraint on force
            force_3: [0, 0, 0, 0, 0, 1] # direction of a third contraint on force
            momentum_1: [0, 0, 0, 0, 0, 0] # direction of a first contraint on momentum
            momentum_2: [0, 0, 0, 0, 0, 0] # direction of a second contraint on momentum
            momentum_3: [0, 0, 0, 0, 0, 0] # direction of a third contraint on momentum
         type: ground
         topic: /raw_contacts_foot_1
         group: front_left_leg # optional, srdf chain with which contact is associated with
      contact2:
         name: front_right_leg
         end_frame: knee_2
         position: [0, 0, -0.30]
         constraint_matrix:
            force_1: [0, 0, 0, 1, 0, 0] # direction of a first contraint on force 
            force_2: [0, 0, 0, 0, 1, 0] # direction of a second contraint on force
            force_3: [0, 0, 0, 0, 0, 1] # direction of a third contraint on force
            momentum_1: [0, 0, 0, 0, 0, 0] # direction of a first contraint on momentum
            momentum_2: [0, 0, 0, 0, 0, 0] # direction of a second contraint on momentum
            momentum_3: [0, 0, 0, 0, 0, 0] # direction of a third contraint on momentum
         type: ground
         topic: /raw_contacts_foot_2
         group: front_right_leg # optional, srdf chain with which contact is associated with
      contact3:
         name: rear_right_leg
         end_frame: knee_3
         position: [0, 0, -0.30]
         constraint_matrix:
            force_1: [0, 0, 0, 1, 0, 0] # direction of a first contraint on force 
            force_2: [0, 0, 0, 0, 1, 0] # direction of a second contraint on force
            force_3: [0, 0, 0, 0, 0, 1] # direction of a third contraint on force
            momentum_1: [0, 0, 0, 0, 0, 0] # direction of a first contraint on momentum
            momentum_2: [0, 0, 0, 0, 0, 0] # direction of a second contraint on momentum
            momentum_3: [0, 0, 0, 0, 0, 0] # direction of a third contraint on momentum
         type: ground
         topic: /raw_contacts_foot_3
         group: rear_right_leg # optional, srdf chain with which contact is associated with
      contact4:
         name: rear_left_leg
         end_frame: knee_4
         position: [0, 0, -0.30]
         constraint_matrix:
            force_1: [0, 0, 0, 1, 0, 0] # direction of a first contraint on force 
            force_2: [0, 0, 0, 0, 1, 0] # direction of a second contraint on force
            force_3: [0, 0, 0, 0, 0, 1] # direction of a third contraint on force
            momentum_1: [0, 0, 0, 0, 0, 0] # direction of a first contraint on momentum
            momentum_2: [0, 0, 0, 0, 0, 0] # direction of a second contraint on momentum
            momentum_3: [0, 0, 0, 0, 0, 0] # direction of a third contraint on momentum
         type: ground
         topic: /raw_contacts_foot_4
         group: rear_left_leg # optional, srdf chain with which contact is associated with
