blacklist:
- examples
- moveit_msgs
- moveit_core
- moveit_simple_controller_manager
- moveit_ros_control_interface
- moveit_ros_perception
- moveit_ros_planning
- moveit_ros_robot_interaction
- moveit_ros_warehouse
- moveit_ros_benchmarks
- moveit_kinematics
- moveit_controller_manager_example
- moveit_fake_controller_manager
- moveit_visual_tools
- moveit_ros_move_group
- moveit_experimental
- moveit_ros_manipulation
- moveit_planners_ompl
- chomp_motion_planner
- moveit_ros_planning_interface
- moveit_planners_chomp
- moveit_ros_visualization
- moveit_setup_assistant
- moveit_commander
- gazebo_tutorials
- object_recognition_msgs
- geometric_shapes
- collision_model_ros_extension
- reference_generation
- collision_model
- visualization_tools
- mgnss_plugins_misc
- mgnss_ros_callbacks_misc
- mgnss_controllers_misc
- mwoibn_xbot_common
- communication_modules_xbot
- robot_class_xbot
build_space: build_release
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
- -DCMAKE_C_FLAGS=-Wall -W -Wno-unused-parameter
- -DLOGGER=ON
- -DEXAMPLES=ON
- -DODOMETRY=ON
- -DGROUND_FORCES=ON
- -DVISUALIZATION_MODULE=OFF
- -DVISUALIZATION_TOOLS=OFF
- -DCOLLISION_CHECK=OFF
- -DTRAJECTORY_GENERATION=OFF
- -DCENTRALIZED_CONTROLLER=ON
- -DCENTER_OF_MASS_CONTROLLER=OFF
- -DCUSTOM_CONTROLLER=ON
- -DGAZEBO_FLOATING_BASE=ON
- -DWHEELS_MOTION=ON
- -DTEST_TEMP=ON
- -DJOINT_STATES=ON
- -DROS=ON
- -DXBOT=ON
- -DGRAVITY_TEST=OFF
- -DHANDLERS=OFF
- -DROS_CONTROL=ON
- -DCATKIN_ENABLE_TESTING=OFF
- -DADVR_SUPERBUILD_DIR=/home/malgorzata/ADVR-Humanoids/advr-superbuild
- -DDRIVING_FRAMEWORK_WORKSPACE="/home/malgorzata/catkin_ws/src/"
- -DYCM_DIR=/home/malgorzata/ADVR-Humanoids/advr-superbuild/build/external/YCM/
devel_layout: linked
devel_space: devel_release
extend_path: null
install: true
install_space: install_release
isolate_install: false
jobs_args: []
log_space: logs_release
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
