#!/usr/bin/env python2.7
from custom_services.srv import updatePDGains
import rospy
from numpy import cos, sin

if __name__ == '__main__':
    rospy.init_node('wheel_reference')
    dt = 0.005
    rate = rospy.Rate(1.0/dt)
    #print(1.0/dt)
    name = '/centauro/wheels_command'
    service_ok = False
    while (not rospy.is_shutdown() and not service_ok):
      try:
        print('wait for service: update_links')
        rospy.wait_for_service(name, 0.5)
        service_ok = True
        print('service found')
      except:
        pass

    rate.sleep()

    ref_service = rospy.ServiceProxy(name, updatePDGains)

    dth, r, th, magic = -0.2, 0.5, 0.0, 2.05

    x, y = 0, 0
    
    mode = 0

    vel_max, vel = 0.5, 0.5
#    ref_service(1.0, 4.0, dth*100)

    dx, dy =  vel,  0.00

    while not rospy.is_shutdown():
#      th = th + dth * dt * magic

#      # square
      if (mode == 0 and x > 1.5 and x < 2.0):
        dx, dy =  vel_max/2,  0.00        
        mode += 1
      elif (mode == 1 and x > 2.0):
        dx, dy = 0.00,  vel_max/2
        mode += 1
      elif (mode == 2 and y > 0.5):
        dx, dy = 0.00,  vel_max
        mode += 1
      elif (mode == 3 and y > 1.5):
        dx, dy = 0.00,  vel_max/2
        mode += 1
      elif (mode == 4 and y > 2.0):
        dx, dy = -vel_max/2,  0.00
        mode += 1
      elif (mode == 5 and x < 1.5):
        dx, dy = -vel_max,  0.00
        mode += 1
      elif (mode == 6 and x < 0.5):
        dx, dy = -vel_max/2,  0.00
        mode += 1
      elif (mode == 7 and x > 0.0):
        dx, dy = 0.00,  -vel_max/2
        mode += 1
      elif (mode == 8 and y < 1.5):
        dx, dy = 0.00,  -vel_max
        mode += 1
      elif (mode == 9 and y < 0.0):
        dx, dy = 0.00,  0.00
        mode += 1

#      dx = -r*cos(th)*dth*100.0
#      dy = -r*sin(th)*dth*100.0
      x += dx*0.005*2
      y += dy*0.005*2
      
      print("dx\t", dx, "dy\t", dy, "th\t", th, "x\t", x,  "y\t", y)

      try:
        ref_service(1.0, 1.0, dx*100.0)
        ref_service(1.0, 2.0, dy*100.0)


      except rospy.ServiceException as exc:
        print("Service did not process request: " + str(exc))


      rate.sleep()




