#!/usr/bin/env python2.7
from custom_services.srv import updatePDGains
import rospy
from numpy import cos, sin, sqrt
import copy

if __name__ == '__main__':
    rospy.init_node('wheel_reference')
    dt = 0.005
    rate = rospy.Rate(1.0/dt)
    #print(1.0/dt)
    name = '/centauro/wheels_command'
    service_ok = False
    while (not rospy.is_shutdown() and not service_ok):
      try:
        print('wait for service: update_links')
        rospy.wait_for_service(name, 0.5)
        service_ok = True
        print('service found')
      except:
        pass

    rate.sleep()

    ref_service = rospy.ServiceProxy(name, updatePDGains)

    r1, r2, th = 1.0, 0.65, 0.0
#    m_d, m_v, vel = 3.05, 2.75, 0.05
    m_d, m_2d, m_v, vel, d_th = 2.0, 2.75, 2.75, 1.00, 0.5*0.5
    x, y = 0, 0
    
    mode = 0


#    ref_service(1.0, 4.0, dth*100)
    vel_max = 0.1
    vel = 0.1
    dx, dy, dth =  0.0,0.0,0.0
    wait = 0    
#    mode, dth = 1, -0.25
    while not rospy.is_shutdown():
#      # square
      if mode == 0 and x < 1.13:
		dx = 0.16
		dth = 0.2
		wait = 0
      elif mode == 0:
		mode += 1
      elif mode == 1 and  dth > 0.0:
		dth -= 0.002 if dth > 0.0 else 0.0
		dx += 0.002 if dx < 0.2 else 0.0  
      elif mode == 1:
		mode += 1
      elif mode == 2 and x > 1.8:
		dx = 0.0        
		mode += 1
		wait = 0
      elif mode == 3:
		wait += 1        
		mode += 1 if wait > 50 else 0
      elif mode == 4 and dth > -0.2:
		dth -= 0.05 if dth > -0.2 else 0.0
		wait = 0
		dx = 0.0
      elif mode == 4:
#		  mode += 1
		wait += 1
		mode += 1 if wait > 545 else 0
      elif mode == 5 and dth < 0.0:
		  wait = 0
		  dth += 0.002
      elif mode == 5:
		  mode += 1
		  dx = -0.015
      elif mode == 6:
        ref_service(16.0, 0.0, 0.0)
        ref_service(16.0, 1.0, 0.0)
        ref_service(16.0, 2.0, 0.0)
        ref_service(16.0, 3.0, 0.0)
        mode += 1
      elif mode == 7:
		wait += 1        
		mode += 1 if wait > 150 else 0	
		if wait == 150:
			ref_service(17.0, 2.0, 0.0)
			ref_service(17.0, 1.0, 0.0)
#		if wait == 150:
#			ref_service(17.0, 0.0, 0.0)
#		if wait == 100:
		if wait == 100:
			ref_service(17.0, 3.0, 0.0)
		if wait == 130:
			ref_service(17.0, 0.0, 0.0)
			
      elif mode == 8:
		  dx = -0.20
		  mode += 1
		  wait = 0
      elif mode == 9 and x < 0.2:
		  dx = -0.0
		  mode += 1

	


      x += dx*dt*m_v
      y += dy*dt*m_v
      
      print("mode\t", mode, "vel\t", sqrt(dx*dx+dy*dy), "dx", dx, "dy", dy, "th\t", th, "dth\t", dth, "x", x, "wait", wait)

      try:
        ref_service(1.0, 1.0, dx*100.0)
        ref_service(1.0, 2.0, dy*100.0)
        ref_service(1.0, 4.0, dth*100.0)

      except rospy.ServiceException as exc:
        print("Service did not process request: " + str(exc))


      rate.sleep()




