joint_map:
  16: hip_yaw_1
  17: hip_pitch_1
  18: knee_pitch_1
  28: ankle_pitch_1
  29: ankle_yaw_1
  30: j_wheel_1
  19: hip_yaw_2
  20: hip_pitch_2
  21: knee_pitch_2
  31: ankle_pitch_2
  32: ankle_yaw_2
  33: j_wheel_2
  22: hip_yaw_3
  23: hip_pitch_3
  24: knee_pitch_3
  34: ankle_pitch_3
  35: ankle_yaw_3
  36: j_wheel_3
  25: hip_yaw_4
  26: hip_pitch_4
  27: knee_pitch_4
  37: ankle_pitch_4
  38: ankle_yaw_4
  39: j_wheel_4
#  99: imu_joint
