mwoibn:        
        robot:
                reference:
                        controller: 
                                list: []
                        actuators: 
                                read: "true"
        xbot:
                source:
#                        urdf: "/home/centauro/src/catkin_malgorzata/src/DrivingFramework/locomotion_framework/xbot/robot_class_xbot/include/configs/urdf/centauro_lower_body.urdf"
                        urdf: 
                                file: "DrivingFramework/locomotion_framework/xbot/robot_class_xbot/include/configs/urdf/centauro.urdf"
                        controller: 
                                file: "ComplianceRos/centauro_control/config/compliance_gains_medium_new.yaml" 


