joint_map:
  1: torso_yaw
  2: j_arm2_1
  3: j_arm2_2
  4: j_arm2_3
  5: j_arm2_4
  6: j_arm2_5
  7: j_arm2_6
  8: j_arm2_7
  9: j_arm1_1
  10: j_arm1_2
  11: j_arm1_3
  12: j_arm1_4
  13: j_arm1_5
  14: j_arm1_6
  15: j_arm1_7
  81: j_arm1_8
  71: hip_yaw_1
  72: hip_pitch_1
  73: knee_pitch_1
  74: ankle_pitch_1
  75: ankle_yaw_1
  76: j_wheel_1
  41: hip_yaw_2
  42: hip_pitch_2
  43: knee_pitch_2
  44: ankle_pitch_2
  45: ankle_yaw_2
  46: j_wheel_2
  61: hip_yaw_3
  62: hip_pitch_3
  63: knee_pitch_3
  64: ankle_pitch_3
  65: ankle_yaw_3
  66: j_wheel_3
  51: hip_yaw_4
  52: hip_pitch_4
  53: knee_pitch_4
  54: ankle_pitch_4
  55: ankle_yaw_4
  56: j_wheel_4
  #80: j_ft_arm2
  18: imu_joint
  101: neck_yaw
  102: neck_pitch
  103: neck_velodyne
  98: j_fl_foot_ft
  97: j_fr_foot_ft
  96: j_hl_foot_ft
  95: j_hr_foot_ft
