mwoibn:
        robot:
                rate: 500
        modules:
                odometry:
                        filter:
                                damping: 1
                                cut_off_frequency: 500
                        velocity:
                                damping: 4
                                cut_off_frequency: 500
                acceleration_test:
                        filter:
                                damping: 2.0
                                cut_off_frequency: 500
                ground_forces:
                        filter:
                            torque:
                                damping: 4.0
                                cut_off_frequency: 500
