mwoibn:
        controller:
                position_controller: # control only the robot lower-body
                        dofs:
                                chain: position_lower_body
        ros: # change the robot urdf source to the lower-body urdf
                source:
                       urdf: "/robot_lower_body"
                       srdf: "/robot_srdf"
        xbot: # change the robot urdf source to the lower-body urdf
                source:
                        urdf:
                                file: "mwoibn/urdf/centauro_lower_body.urdf"

