
mwoibn:
        # controller:
        #         position_controller:
        #                 dofs:
        #                         chain: upper_body
        ros:
                source:
                       urdf: "/robot_upper_body"
        xbot:
                source:
                       urdf:
                              file: mwoibn/urdf/centauro_upper_body.urdf

        controllers:
                position_reference:
                        list: [upper_body]
        feedbacks:
                online: [link_side_online]

#                       srdf: "/robot_srdf"
#        xbot:
#                source:
#                        urdf:
#                                file: "DrivingFramework/locomotion_framework/xbot/robot_class_xbot/include/configs/urdf/centauro_lower_body.urdf"
#                        srdf:
#                                file: "DrivingFramework/locomotion_framework/xbot/robot_class_xbot/include/configs/srdf/centauro_full_wheels.srdf"
