
mwoibn:
        # controller:
        #         position_controller:
        #                 dofs:
        #                         chain: upper_body
        ros: # cheange the urdf to the upper-body
                source:
                       urdf: "/robot_upper_body"
        xbot:
                source:
                       urdf:
                              file: mwoibn/urdf/centauro_upper_body.urdf

        controllers:
                position_reference:
                        list: [upper_body] # control only the upper-body
        feedbacks:
                online: [link_side_online] # remove the state estimation from the deafult feedbacks, upper-body is a static model

