XBotCore:
  config_path: "configs/ADVR_shared/centauro/configs/centauro.yaml"

XBotInterface:
  urdf_path: "configs/ADVR_shared/centauro/urdf/centauro.urdf"
  srdf_path: "configs/ADVR_shared/centauro/srdf/centauro.srdf"
  joint_map_path: "configs/ADVR_shared/centauro/joint_map/centauro_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"
  
MasterCommunicationInterface:
  framework_name: "ROS"

XBotRTPlugins:
#  plugins: ["Odometry", "JointStates", "WheelsV2"]
  plugins: ["JointStates", "Odometry", "WheelsV2"]
#  plugins: ["JointStates", "Odometry"]
  io_plugins: []
  
NRTPlugins:
#  plugins: ["HomingExample"]
  plugins: []
WebServer:
  enable: "false"
  address: "127.0.0.1"
  port: "8081"

SimulationOptions:
  verbose_mode: "false"    

GazeboXBotPlugin:
  control_rate: 0.001
  gains:
    j_arm1_1: {p: 2000, d: 3}
    j_arm1_2: {p: 2000, d: 3}
    j_arm1_3: {p: 2000, d: 3}
    j_arm1_4: {p: 2000, d: 3}
    j_arm1_5: {p: 300,  d: 3}
    j_arm1_6: {p: 2000, d: 5}
    j_arm1_7: {p: 300, d: 2}
    j_arm2_1: {p: 2000, d: 3}
    j_arm2_2: {p: 2000, d: 5}
    j_arm2_3: {p: 2000, d: 3}
    j_arm2_4: {p: 2000, d: 3}
    j_arm2_5: {p: 300,  d: 3}
    j_arm2_6: {p: 2000, d: 5}
    j_arm2_7: {p: 300, d: 2}
    torso_yaw: {p: 4000, d: 3}
    hip_yaw_1:  &hip_yaw {p: 5000, d: 2}
    hip_yaw_2: *hip_yaw
    hip_yaw_3: *hip_yaw
    hip_yaw_4: *hip_yaw
    hip_pitch_1: &hip_pitch {p: 5000, d: 2}
    hip_pitch_2: *hip_pitch
    hip_pitch_3: *hip_pitch
    hip_pitch_4: *hip_pitch
    knee_pitch_1: &knee_pitch {p: 5000, d: 2}
    knee_pitch_2: *knee_pitch
    knee_pitch_3: *knee_pitch
    knee_pitch_4: *knee_pitch
    ankle_pitch_1: &ankle_pitch {p: 5000, d: 2}
    ankle_pitch_2: *ankle_pitch
    ankle_pitch_3: *ankle_pitch
    ankle_pitch_4: *ankle_pitch
    ankle_yaw_1: &ankle_yaw {p: 5000, d: 2}
    ankle_yaw_2: *ankle_yaw
    ankle_yaw_3: *ankle_yaw
    ankle_yaw_4: *ankle_yaw    
    j_wheel_1: &wheel {p: 0, d: 5}
    j_wheel_2: *wheel
    j_wheel_3: *wheel
    j_wheel_4: *wheel

mwoibn:
   config_file: &config /home/embedded/locomotion_src/workspace/src/DrivingFramework/locomotion_framework/configs/mwoibn_v2_5.yaml
