mwoibn:
        robot:
                name: "centauro"
                default:
                        rate: 200
                        controller: 
                                layer: "lower_level"
                        feedback: 
                                layer: "online"
                        actuators: 
                                read: "true"
                        contacts: 
                                read: "true"
                                feedback: false

                reference:
                        rate: 200
                        controller: 
                                list: ["whole_body"]
                        feedback: 
                                layer: "offline"
                        actuators: 
                                read: "false"
                        contacts: 
                                read: "true"
                                feedback: false

                higher_scheme:
                        rate: 200
                        controller: 
                                layer: "higher_level"
                        feedback: 
                                layer: "online"
                        actuators: 
                                read: "true"
                        contacts: 
                                read: "true"
                                feedback: false  
                empty:
                        rate: 200
                        controller: 
                                layer: ""
                        feedback: 
                                layer: ""
                        actuators: 
                                read: false
                        contacts: 
                                read: false
                                feedback: false  
        feedback:
                link_side_online: 
                        space: JOINT
                        dofs: 
                                chain: all
                                type: actuated
                                mapping: PYTHON
                        interface:
                                position: true
                                velocity: false
                                effort: false                               
                motor_side_online:
                floating_base:
                        space: OPERATIONAL 
                        convention:
                                orientation:
                                        type: QUATERNION
                                        convention: HAMILTONIAN
                        dofs: 
                                chain: all
                                type: body
                                name: pelvis
                                mapping: RBDL
                        interface:
                                position: true
                                velocity: false
                                effort: false  		
                whole_body:
                        space: JOINT
                        dofs: 
                                chain: all
                                type: all
                                mapping: RBDL
                        interface:
                                position: true
                                velocity: true
                                effort: false
        controller:
                position_controller:
                        dofs: 
                                chain: all
                                type: actuated
                                mapping: PYTHON
                        interface:
                                position: true
                                velocity: false
                                effort: true
                velocity_controller:
                        dofs: 
                                chain: all
                                type: actuated
                                mapping: PYTHON
                        interface:
                                position: false
                                velocity: true
                                effort: false
                whole_body:
                        dofs: 
                                chain: all
                                type: all
                                mapping: RBDL
                        interface:
                                position: true
                                velocity: true
                                effort: false
        feedbacks:
                online: [link_side_online, motor_side_online, floating_base]
                offline: [whole_body]
        controllers:
                lower_level: [position_controller, velocity_controller]
                higher_level: [whole_body]
        ros:
                mapping:
                        PYTHON:
                                source: "joint_states"
                                message: sensor_msgs::JointState
                source:
                        urdf: "/robot_description"
                        srdf: "/robot_semantic_description"
                        actuators: "actuators_yaml"
                        contacts: "contacts_yaml"
                feedback:
                        link_side_online: 
                                source: "joint_states"
                                message: sensor_msgs::JointState
                                initialize: true
                        floating_base: 
                                source: "/gazebo/link_states"
                                message: gazebo_msgs::LinkStates
                                reference: 1
                                initialize: true
                        whole_body:
                                source2: "position_controller/reference"
                                source: "desired_state"
                                message: custom_messages::CustomCmnd
                                initialize: false
                        motor_side_online: 
                                space: SKIP
                                
                controller:
                        position_controller:
                                type: custom_controller/ActuatorPositionControllerClasses
                                sink: /command
                                ff_service: /set_ff_torque
                        velocity_controller:
                                type: custom_controller/ActuatorVelocityController
                                sink: /command
                        whole_body:
                                type: "reference"
                                sink2: "position_controller/reference"
                                sink: "desired_state"
        xbot:
                source:
                        config: "/home/malgorzata/catkin_ws/src/DrivingFramework/locomotion_framework/xbot/robot_class_xbot/include/configs/config_centauro.yaml"
                        urdf: "/home/malgorzata/catkin_ws/src/DrivingFramework/locomotion_framework/xbot/robot_class_xbot/include/configs/urdf/centauro_lower_body.urdf"
#                        urdf: "/home/user/malgorzata/workspace/src/locomotion_framework/xbot/robot_class_xbot/include/configs/urdf/centauro_full_wheels.urdf"
#                        srdf: "/home/user/malgorzata/workspace/src/locomotion_framework/xbot/robot_class_xbot/include/configs/srdf/centauro_full_wheels.srdf"
                        actuators: "/home/malgorzata/catkin_ws/src/centauro-simulator/centauro/centauro_config/config/actuators_new.yaml"
                        contacts: "/home/malgorzata/catkin_ws/src/centauro-simulator/centauro/centauro_config/config/contacts.yaml" 
                feedback:
                        link_side_online:
                                layer: online
                                dofs:
                                        mapping: XBOT
                        motor_side_online:
                                layer: online
                                space: SKIP
                        floating_base:
                                layer: NRT
                                sensor: imu_link
                                source: "floating_base"
                        whole_body: 
                                layer: NRT
                                source: "desired_state"
                controller:
                        position_controller:
                                layer: lower_level
                                dofs:
                                        mapping: XBOT
                        velocity_controller:
                                layer: lower_level
                                dofs:
                                        mapping: XBOT
                        whole_body:
                                layer: NRT
                                sink: "desired_state"
                                 
                              
