driving_path: &driving  "/home/centauro/src/catkin_malgorzata/src/"
simulator_path: &simulator "/home/centauro/devel-superbuild/robots/"
mwoibn:
        middleware: "XBOT"
        robot:
                name: "centauro"
                default:
                        type: "NRT"
                        rate: 200
                        controller: 
                                list: [position_controller, velocity_controller]
                        feedback: 
                                layer: "online"
                        actuators: 
                                read: "true"
                        contacts: 
                                read: "true"
                                feedback: false

                reference:
                        rate: 200
                        type: "NRT"
                        controller: 
                                list: ["lower_body"]
                        feedback: 
                                layer: "offline"
                        actuators: 
                                read: "false"
                        contacts: 
                                read: "true"
                                feedback: false

                higher_scheme:
                        rate: 200
                        type: "NRT"
                        controller: 
                                layer: "higher_level"
                        feedback: 
                                layer: "online"
                        actuators: 
                                read: "true"
                        contacts: 
                                read: "true"
                                feedback: false
                full_model:
                        rate: 200
                        type: "NRT"
                        controller: 
                                list: []
                        feedback: 
                                layer: "online"
                        actuators: 
                                read: "true"
                        contacts: 
                                read: "true"
                                feedback: false  
                simulated:
                        rate: 1000
                        type: "NRT"
                        controller: 
                                layer: ""
                        feedback: 
                                layer: "simulated"
                        actuators: 
                                read: "true"
                        contacts: 
                                read: "true"
                                feedback: false  
                empty:
                        rate: 200
                        type: "NRT"
                        controller: 
                                layer: ""
                        feedback: 
                                layer: ""
                        actuators: 
                                read: false
                        contacts: 
                                read: false
                                feedback: false  
                odometry:
                        rate: 200
                        type: "NRT"
                        controller: 
                                list: [odometry]
                        feedback: 
                                list: [link_side_online, imu_base]
                        actuators: 
                                read: true
                        contacts: 
                                read: true
                                feedback: false 
                joint_space:
                        rate: 200
                        type: "NRT"
                        controller: 
                                layer: "lower_level"
                        feedback: 
                                list: [link_side_online]
                        actuators: 
                                read: true
                        contacts: 
                                read: false
                                feedback: false


        feedback:
                link_side_online: 
                        space: JOINT
                        dofs: 
                                chain: all
                                type: actuated
                                mapping: PYTHON
                        interface:
                                position: true
                                velocity: false
                                effort: false    
                simulation_state: 
                        space: JOINT
                        dofs: 
                                chain: all
                                type: actuated
                                mapping: PYTHON
                        interface:
                                position: true
                                velocity: true
                                effort: false                              
                motor_side_online:
                floating_base:
                        space: OPERATIONAL 
                        convention:
                                orientation:
                                        type: QUATERNION
                                        convention: HAMILTONIAN
                                position:
                                        type: FULL
                        dofs: 
                                chain: all
                                type: body
                                name: pelvis
                                mapping: RBDL
                        interface:
                                position: true
                                velocity: false
                                effort: false
                simulation_base:
                        space: OPERATIONAL 
                        convention:
                                orientation:
                                        type: QUATERNION
                                        convention: HAMILTONIAN
                                position:
                                        type: FULL
                        dofs: 
                                chain: all
                                type: body
                                name: pelvis
                                mapping: RBDL
                        interface:
                                position: true
                                velocity: true
                                effort: false
                imu_base:
                        space: OPERATIONAL 
                        convention:
                                orientation:
                                        type: QUATERNION
                                        convention: HAMILTONIAN
                                position:
                                        type: NONE
                        dofs: 
                                chain: all
                                type: body
                                name: pelvis
                                mapping: RBDL
                        interface:
                                position: true
                                velocity: false
                                effort: false
                whole_body:
                        space: JOINT
                        dofs: 
                                chain: all
                                type: all
                                mapping: RBDL
                        interface:
                                position: true
                                velocity: true
                                effort: false
                lower_body:
                        space: JOINT
                        dofs: 
                                chain: lower_body
                                type: all
                                mapping: RBDL_LOWER #this has to be to indiacate the RBDL model that it is working with is only lower body
                        interface:
                                position: true
                                velocity: true
                                effort: false
                odometry:
                        space: JOINT
                        dofs: 
                                chain: base
                                type: all
                                mapping: RBDL_LOWER #this has to be to indiacate the RBDL model that it is working with is only lower body
                        interface:
                                position: true
                                velocity: false
                                effort: false
                velocity_reference:
                        space: JOINT
                        dofs: 
                                chain: lower_body
                                type: all
                                mapping: RBDL_LOWER #this has to be to indiacate the RBDL model that it is working with is only lower body
                        interface:
                                position: false
                                velocity: true
                                effort: false
        controller:
                position_controller:
                        dofs: 
                                chain: position
                                type: actuated
                                mapping: PYTHON
                        interface:
                                position: true
                                velocity: false
                                effort: true
                        initialize: "link_side_online"
                velocity_controller:
                        dofs: 
                                chain: wheels
                                type: actuated
                                mapping: PYTHON
                        interface:
                                position: false
                                velocity: true
                                effort: false
                whole_body:
                        dofs: 
                                chain: all
                                type: all
                                mapping: RBDL
                        interface:
                                position: true
                                velocity: true
                                effort: false
                lower_body:
                        dofs: 
                                chain: lower_body
                                type: all
                                mapping: RBDL #this he RBDL model that it is working with is only lower body
                        interface:
                                position: true
                                velocity: true
                                effort: false
                                effort: false
                odometry:
                        dofs: 
                                chain: base
                                type: all
                                mapping: RBDL_LOWER #this he RBDL model that it is working with is only lower body
                        interface:
                                position: true
                                velocity: false
                                effort: false
        feedbacks:
                online: [link_side_online, motor_side_online, odometry]
                offline: [lower_body]
                simulated: [simulation_base, simulation_state]
        controllers:
                lower_level: [position_controller, velocity_controller]
                higher_level: [lower_body]

        ros:
                mapping:
                        PYTHON:
                                loading: topic
                                source: "joint_states"
                                message: sensor_msgs::JointState
                        RBDL_LOWER:
                                loading: model
                                urdf: "/robot_lower_body"
                source:
                        urdf: "/robot_description"
                        srdf: "/robot_srdf"
                        actuators: "actuators_yaml"
                        contacts: "contacts_yaml"
                feedback:
                        link_side_online: 
                                source: "joint_states"
                                message: sensor_msgs::JointState
                                initialize: true
                        simulation_state: 
                                source: "joint_states"
                                message: sensor_msgs::JointState
                                initialize: true
                        simulation_base: 
                                source: "/gazebo/link_states"
                                message: gazebo_msgs::LinkStates
                                reference: 1
                                initialize: true
                        floating_base: 
                                source: "/gazebo/link_states"
                                message: gazebo_msgs::LinkStates
                                reference: 1
                                initialize: true
                        imu_base: 
                                source: "/gazebo/link_states"
                                message: gazebo_msgs::LinkStates
                                reference: 1
                                initialize: true
                        whole_body:
                                source2: "position_controller/reference"
                                source: "desired_state"
                                message: custom_messages::CustomCmnd
                                initialize: false
                        lower_body:
                                source: "desired_state"
                                message: custom_messages::CustomCmnd
                                initialize: false
                        odometry:
                                source: "base_odometry"
                                message: custom_messages::CustomCmnd
                                initialize: true
                        velocity_reference:
                                source: "desired_state"
                                message: custom_messages::CustomCmnd
                                initialize: false
                        motor_side_online: 
                                space: SKIP
                                
                controller:
                        position_controller:
                                type: custom_controller/ActuatorPositionControllerClasses
                                sink: /command
                                ff_service: /set_ff_torque
                        velocity_controller:
                                type: custom_controller/ActuatorVelocityController
                                sink: /command
                        whole_body:
                                type: "reference"
                                sink2: "position_controller/reference"
                                sink: "desired_state"
                        lower_body:
                                type: "reference"
                                sink: "desired_state"
                        odometry:
                                type: "reference"
                                sink: "base_odometry"
        xbot:
                source:
                        config: 
                                path: *driving
                                file: "DrivingFramework/locomotion_framework/xbot/robot_class_xbot/include/configs/centauro_working_jan_2018.yaml"
                        urdf: 
                                path: *driving
                                file: "DrivingFramework/locomotion_framework/xbot/robot_class_xbot/include/configs/urdf/centauro.urdf"
#                        urdf: "/home/user/malgorzata/workspace/src/locomotion_framework/xbot/robot_class_xbot/include/configs/urdf/centauro_full_wheels.urdf"
                        srdf:
                                path: *driving
                                file: "DrivingFramework/locomotion_framework/xbot/robot_class_xbot/include/configs/srdf/centauro_full_wheels.srdf"
                        actuators: 
                                path: *simulator
                                file: "centauro-simulator/centauro/centauro_config/config/actuators_new.yaml"
                        contacts: 
                                path: *simulator 
                                file: "centauro-simulator/centauro/centauro_config/config/contacts.yaml"
                        controller: 
                                path: *driving
                                file: "" 
                mapping:
                        RBDL_LOWER:
                                loading: model
                                urdf: 
                                        path: *driving
                                        file: "DrivingFramework/locomotion_framework/xbot/robot_class_xbot/include/configs/urdf/centauro_lower_body.urdf"
                feedback:
                        link_side_online:
                                layer: online
                                dofs:
                                        mapping: XBOT
                        velocity_online:
                                layer: online
                                dofs:
                                        mapping: XBOT
                        motor_side_online:
                                layer: online
                                space: SKIP
                        floating_base:
                                layer: NRT
                                sensor: imu_link
                                source: "floating_base"
                        imu_base:
                                layer: online
                                sensor: imu_link
                                source: "floating_base"
                        whole_body: 
                                layer: NRT
                                source: "desired_state"
                        velocity_reference: 
                                layer: NRT
                                source: "desired_state"
                        lower_body: 
                                layer: NRT
                                source: "desired_state"
                        odometry: 
                                layer: NRT
                                source: "base_odometry"
                controller:
                        position_controller:
                                layer: lower_level
                                dofs:
                                        mapping: XBOT
                        velocity_controller:
                                layer: lower_level
                                dofs:
                                        mapping: XBOT
                        whole_body:
                                layer: NRT
                                sink: "desired_state"
                        lower_body:
                                layer: NRT
                                sink: "desired_state"
                        odometry:
                                layer: NRT
                                sink: "base_odometry"
                                 
                              
