mwoibn:
        robot:
                rate: 500
        modules:
                odometry:
                        filter:
                                damping: 1
                                cut_off_frequency: 500

