mwoibn:
        robot:
                rate: 1000
        modules:
                odometry:
                        filter:
                                damping: 1
                                cut_off_frequency: 1000
                                
